services:
  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
    container_name: redis

  app:
    image: app:latest
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs   # 호스트 ./logs ↔ 컨테이너 /app/logs 연결
    user: "1000:1000"
    restart: always
    container_name: survey-app
    env_file:
      - .env
    depends_on:
      - redis
      - kafka

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/ec2-user/nginx:/etc/nginx/conf.d
      - /home/ec2-user/certbot/conf:/etc/letsencrypt
      - /home/ec2-user/certbot/www:/var/www/certbot
    depends_on:
      - app

#  certbot:
#    image: certbot/certbot
#    command: certonly --webroot --non-interactive --agree-tos --webroot-path=/var/www/certbot -d surmile.o-r.kr
#    volumes:
#      - /home/ec2-user/certbot/conf:/etc/letsencrypt
#      - /home/ec2-user/certbot/www:/var/www/certbot
#    depends_on:
#      - nginx
