services:
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
    container_name: redis

  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs   # 호스트 ./logs ↔ 컨테이너 /app/logs 연결
    command: >
      sh -c "java -jar /app/app.jar >> /app/logs/app.log 2>&1"
    restart: always
    container_name: survey-app
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/ec2-user/nginx:/etc/nginx/conf.d
      - /home/ec2-user/certbot/conf:/etc/letsencrypt
      - /home/ec2-user/certbot/www:/var/www/certbot
    depends_on:
      - app

#  certbot:
#    image: certbot/certbot
#    command: certonly --webroot --non-interactive --agree-tos --webroot-path=/var/www/certbot -d xn--hz2b19osld.o-r.kr
#    volumes:
#      - /home/ec2-user/certbot/conf:/etc/letsencrypt
#      - /home/ec2-user/certbot/www:/var/www/certbot
#    depends_on:
#      - nginx
