name: Spring Boot Application Deploy
on:
  push:
    branches: [ "dev" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git repository checkout
        uses: actions/checkout@v4

      - name: JDK 17 설치
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 파일 전송을 위한 디렉토리 생성
        run: mkdir ./survey-app #.env, app.jar

      - name: Gradle build
        run: ./gradlew clean build

      - name: Archive 파일명 변경
        run: mv ./build/libs/*SNAPSHOT.jar ./survey-app/app.jar

      - name: ENV 파일 생성
        run: echo "${{ secrets.ENV_PROPERTIES }}" > ./survey-app/.env

      - name: SCP로 EC2에 jar 파일 전송
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PEM_KEY }}
          source: ./survey-app # 전송 대상
          target: /home/ec2-user/deploy # 전송 경로

      - name: SSH를 통해 EC2에 접속 후 서비스 재 시작
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PEM_KEY }}
          script: |
            rm -rf /home/ec2-user/rollback
            mkdir /home/ec2-user/rollback
            mv /home/ec2-user/survey-app /home/ec2-user/rollback # 이전 버전 보관
            
            rm -rf /home/ec2-user/survey-app
            mkdir /home/ec2-user/survey-app
            mv /home/ec2-user/deploy/survey-app /home/ec2-user # 새 버전 적용
            
            cd /home/ec2-user/survey-app
            sudo fuser -k -n tcp 8080 || true # 기존 서비스 종료
            nohup java -jar /home/ec2-user/survey-app/app.jar > application-log 2>&1 & # 신규 서비스 시작
            rm -rf /home/ec2-user/deploy